project:
  type: website

website:
  title: "SimBA"
  navbar:
    background: lightgray 
    left:
      - text: "RAMP"
        menu:
        - text: What is RAMP? 
          href: ramp.html 
        - text: Malaria Theory 
          href: https://faculty.washington.edu/smitdave/theory/_site/index.html
        - text: Malaria Data 
          href: https://faculty.washington.edu/smitdave/Malaria_Data/MalariaData.html 
        - text: SimBA (Software)
          href: index.html 
        - text: Adaptive Malaria Control 
          href: https://faculty.washington.edu/smitdave/ramp/_site/index.html
      - text: "Software" 
        menu: 
        - Rpackages.qmd
        - ramp.xds.qmd
        - ramp.library.qmd
        - ramp.control.qmd
        - ramp.forcing.qmd
        - ramp.work.qmd
        - ramp.micro.qmd
        - ramp.falciparum.qmd
        - exDE.qmd
        - MicroMoB.qmd
      - text: "Getting Started" 
        menu: 
        - text: "Demo (Slideshow)"
          href: demo.html
        - href: setup.qmd
      - text: "Models" 
        menu:
        - model534.qmd 
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - ramp.qmd
      - section: Rpackages.qmd
        contents:
        - ramp.xds.qmd
        - ramp.library.qmd
        - ramp.control.qmd
        - ramp.forcing.qmd
        - ramp.work.qmd
        - ramp.micro.qmd
        - ramp.falciparum.qmd
        - exDE.qmd
        - MicroMoB.qmd
      - section: model_building.qmd 
        contents:
          - nimble.qmd
          - progressive.qmd
      - section: transmission.qmd  
        contents:
          - blood_feeding.qmd
          - heterogeneous_transmission.qmd
          - macdonald.qmd
          - behavioral_states.qmd
      - section: malaria_epidemiology.qmd 
        contents:
          - hybrid_models.qmd
      - section: scaling.qmd 
        contents:
          - href: scaling-drugs.html
            text: "Anti-Malarial Drugs"
          - href: scaling-seasonality.html
            text: "Seasonality"
          - href: scaling-environmental_heterogeneity.html
            text: "Environmental Heterogeneity"
          - href: scaling-malaria_importation.html
            text: "Travel Malaria"
      - section: mosquito_ecology.qmd 
        contents:
          - egg_laying.qmd
     
          
format:
  html:
    theme: spacelab 
    css: styles.css
    toc: true
    toc-depth: 2 
    grid: 
      sidebar-width: 350px 
      margin-width: 300px 
      

editor: visual

