project:
  type: website

website:
  title: "SimBA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: demo.qmd 
      - href: setup.qmd
      - text: "Zoo" 
        menu:
        - model534.qmd 
      - Contributors.qmd
      - about.qmd
  sidebar:
    -title: "Software"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: Rpackages.qmd 
        contents:
          - ramp.xds.qmd
          - ramp.library.qmd
          - ramp.control.qmd
          - ramp.forcing.qmd
          - ramp.work.qmd
          - ramp.micro.qmd
          - ramp.falciparum.qmd
          - exDE.qmd
          - MicroMoB.qmd
      - section: model_building.qmd 
        contents:
          - nimble.qmd
          - progressive.qmd
      - section: scaling.qmd 
        contents:
          - href: scaling-drugs.html
            text: "Anti-Malarial Drugs"
          - href: scaling-seasonality.html
            text: "Seasonality"
          - href: scaling-environmental_heterogeneity.html
            text: "Environmental Heterogeneity"
          - href: scaling-malaria_importation.html
            text: "Travel Malaria"
      - section: malaria_epidemiology.qmd 
        contents:
          - hybrid_models.qmd
      - section: transmission.qmd  
        contents:
          - blood_feeding.qmd
          - heterogeneous_transmission.qmd
          - macdonald.qmd
          - behavioral_states.qmd
      - section: mosquito_ecology.qmd 
        contents:
          - egg_laying.qmd
          
format:
  html:
    theme: simplex 
    css: styles.css
    toc: true
    grid: 
      sidebar-width: 350px 

editor: visual

