project:
  type: website

website:
  title: "SimBA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: demo.qmd 
      - href: setup.qmd
      - text: "Zoo" 
        menu:
        - model534.qmd 
      - Contributors.qmd
  sidebar:
    -title: "Software"
    style: "docked"
    search: true
    contents:
      - section: Rpackages.qmd 
        contents:
          - ramp.xds.qmd
          - ramp.library.qmd
          - ramp.control.qmd
          - ramp.forcing.qmd
          - ramp.work.qmd
          - ramp.micro.qmd
          - ramp.falciparum.qmd
          - exDE.qmd
          - MicroMoB.qmd
      - section: model_building.qmd 
        contents:
          - progressive.qmd
      - section: malaria_intelligence.qmd 
        contents:
          - scaling.qmd
      - section: malaria_epidemiology.qmd 
        contents:
          - hybrid_models.qmd
      - section: transmission.qmd  
        contents:
          - blood_feeding.qmd
          - behavioral_states.qmd
          - macdonald.qmd
      - section: mosquito_ecology.qmd 
        contents:
          - egg_laying.qmd
          
format:
  html:
    theme: simplex 
    css: styles.css
    toc: true

editor: visual

