project:
  type: website
  output-dir: ../UW/simba
  render:
    - "*.qmd"
    - "!pipeline_tutorial.qmd"
website:
  title: "SimBA"
  navbar:
    background: lightgray 
    left:
      - icon: github
        menu:
        - text: ramp.xds
          href: https://dd-harp.github.io/ramp.xds/
        - text: ramp.library
          href: https://dd-harp.github.io/ramp.library/
        - text: ramp.func
          href: https://dd-harp.github.io/ramp.func/
        - text: ramp.demog
          href: https://dd-harp.github.io/ramp.demog/
        - text: ramp.forcing
          href: https://dd-harp.github.io/ramp.forcing/
        - text: ramp.qa
          href: https://dd-harp.github.io/ramp.qa/
        - text: ramp.work
          href: https://dd-harp.github.io/ramp.work/
        - text: ramp.falciparum
          href: https://dd-harp.github.io/ramp.falciparum/
        - text: ramp.micro
          href: https://dd-harp.github.io/ramp.micro/
      - text: Home 
        href: index.html
      - text: "Get Started" 
        menu: 
        - demo_install.qmd 
        - demo_build.qmd 
        - demo_solve.qmd
        - demo_viz.qmd
      - text: "Related" 
        menu: 
        - text: "Malaria Theory"
          href:  https://faculty.washington.edu/smitdave/malaria_theory/
        - text: "Robust Analytics"
          href: ramp.html
      - text: Code
        menu: 
        - components.qmd 
        - XHcomponent.qmd
        - MYcomponent.qmd
        - Lcomponent.qmd
        - Vcomponent.qmd
        - interface.qmd 
      - text: "Concepts" 
        menu:
        - complex_adaptive_system.qmd
        - concept_cloud.qmd 
        - nimble.qmd
        - scalable_complexity.qmd
        - progressive.qmd
        - heterogeneous_transmission.qmd
        - malaria_landscape.qmd
        - behavioral_states.qmd
        - zoo.qmd 
      - text: "Reference" 
        menu:
        - glossary.qmd
        - style_guide.qmd
      - text: News
        href: news.html
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: Rpackages.qmd
        contents:
        - section: robust_analytics.qmd
          contents:
          - ramp.xds.qmd 
          - ramp.func.qmd
          - ramp.library.qmd
          - ramp.forcing.qmd 
          - ramp.demog.qmd
          - ramp.work.qmd
          - ramp.qa.qmd
        - section: deep_dives.qmd
          contents:
          - ramp.micro.qmd
          - ramp.falciparum.qmd
        - section: deprecated.qmd
          contents:
          - exDE.qmd
          - MicroMoB.qmd
      - section: demo_simba.qmd
        contents:
        - demo_install.qmd
        - demo_build.qmd 
        - demo_solve.qmd
        - demo_viz.qmd
        - demo_trivial.qmd
        - demo_fitting.qmd
      - section: model_building.qmd 
        contents:
        - basic_setup.qmd
        - advanced_setup.qmd
        - spatial_dynamics.qmd
        - forcing.qmd
        - heterogeneity.qmd
      - section: model_library.qmd 
        contents:
        - malaria_modules.qmd
        - compartmental_X.qmd
        - other_X_modules.qmd
        - adult_modules.qmd
        - aquatic_modules.qmd
      - text: "---"
      - text: "OPTIONS"
      - text: "---"
      - trace.qmd
      - section: malaria_epidemiology.qmd 
        contents:
        - trivialX.qmd
        - time_spent.qmd
        - travel_malaria.qmd
        - stratification.qmd
        - heterogeneous_biting.qmd
        - host_species.qmd
      - section: human_ecology.qmd 
        contents:
        - trivialH.qmd
        - demography.qmd
        - aging.qmd
        - migration.qmd
        - cohort_dynamics.qmd
      - section: adult_mosquito.qmd
        contents: 
        - trivialMY.qmd
        - blood_feeding.qmd
        - mosquito_demography.qmd
        - mosquito_dispersal.qmd
        - resources.qmd
        - weather.qmd
        - indoors.qmd
        - circadian.qmd
        - ento_surveillance.qmd 
      - section: mosquito_ecology.qmd 
        contents:
        - trivialL.qmd
        - mosquito_landscapes.qmd
        - egg_laying.qmd
        - regulation.qmd
        - rainfall.qmd
        - habitat_dynamics.qmd
        - vector_species.qmd
      - section: transmission.qmd 
        contents:
        - malaria_landscapes.qmd
        - exposure.qmd
        - environmental_heterogeneity.qmd
        - visitors.qmd
      - section: vector_control.qmd
        contents:
        - itn.qmd
        - irs.qmd
        - lsm.qmd
        - sugar.qmd
      - section: malaria_control.qmd
        contents:
        - mass_treat.qmd
        - vaccines.qmd
        - other_vaccines.qmd
      - text: "---"
      - text: "Using SimBA"
      - text: "---"
      - section: workflows.qmd 
        contents:
          - solving.qmd
          - visualization.qmd
          - observation.qmd
          - fitting.qmd
      - section: analysis.qmd 
        contents:
          - thresholds.qmd
          - connectivity.qmd
          - scaling.qmd
      - section: analytics.qmd 
        contents:
        - history.qmd
        - effect_size_estimation.qmd  
        - evaluation.qmd
        - baseline.qmd
        - forecasting.qmd
        - scenario_planning.qmd
      - text: "---"
      - text: "Examples"
      - text: "---"
      - section: zoo.qmd 
        contents:
        - section: rossmacdonald.qmd 
          contents:
          - ross1908.qmd
          - ross1911.qmd
          - macdonald1952.qmd
          - aron1982.qmd
        - text: The 5-3-4 Example
          href: https://dd-harp.github.io/ramp.xds/articles/ex_534.html 
        - itn_lemenach.qmd 
        - mda.qmd 
format:
  html:
    theme: spacelab 
    css: styles.css
    toc: true
    toc-depth: 3 
    toc-expand: 1 
    grid: 
      sidebar-width: 350px 
      margin-width: 300px 
      

editor: visual

