---
title: "Scaling Relationships"
subtitle: "Exploring the *Pf*EIR and the *Pf*PR"
---

Load the required packages:

```{r}
library(ramp.xds)
library(ramp.library)
library(ramp.work)
library(deSolve)
library(rootSolve)
library(graphics)
```

## xde_scaling 

The function `xde_scaling()` defines the relationship between the EIR and the PR, and it outputs stable orbits for each value of aEIR in a mesh from $10^{-1}$ up to $10^{3}$ 

The cohort trace functions in `ramp.xds` take the form of `F(a, bday=0, scale=1).` 

```{r Fsin}
tt <- seq(0, 730, by=5) 
p1 <- makepar_F_sin(floor=0.1)
Fsin <- make_function(p1)
plot(tt, Fsin(tt), type="l")
```

```{r sis}
xds_setup_cohort(Xname = "SIS", F_season=Fsin) -> sis
```

```{r solve}
xds_solve_cohort(sis) -> sis
```

```{r scaling}
xde_scaling_eir(sis, 25) -> sis
```

```{r plot, fig.height=3.5, fig.width=5}
plot_eirpr(sis)
```

```{r}
require(viridis)
clrs = turbo(25)
```

```{r, fig.height=3.5, fig.width=5}
plot_eirpr(sis)

with(sis$output$eirpr,{
  points(aeir, pr, col = clrs)
  lines(scaling[[5]]$aeir, scaling[[5]]$pr, col = clrs[5])
  lines(scaling[[10]]$aeir, scaling[[10]]$pr, col = clrs[10])
  lines(scaling[[15]]$aeir, scaling[[15]]$pr, col = clrs[15])
  lines(scaling[[20]]$aeir, scaling[[20]]$pr, col = clrs[20])
})
```


## Scaling {.tabset}

### Seasonality

```{r, eval=F}
sis0 <- xds_setup_cohort(Xname = "SIS", F_season = Fsin)
xde_scaling_eir(sis0, 25) -> sis0
```


```{r, eval=F}
clrs = turbo(25)
with(sis$outputs$eirpr, plot(aeir, pr, type = "l", log = "x", xaxt= "n", xlab = "aEIR", ylab = "PR"))
axis(1, 10^(-1:3), c(0.1, 1, 10, 100, 1000))
lines(sis$outputs$eirpr$aeir, sis0$outputs$eirpr$pr, col = "tomato", lwd=2) 

with(sis0$outputs$eirpr, points(aeir, pr, col = clrs))
with(sis0$outputs$eirpr, lines(scaling[[5]]$aeir, scaling[[5]]$pr, col = clrs[5]))
with(sis0$outputs$eirpr, lines(scaling[[10]]$aeir, scaling[[10]]$pr, col = clrs[10]))
with(sis0$outputs$eirpr, lines(scaling[[15]]$aeir, scaling[[15]]$pr, col = clrs[15]))
with(sis0$outputs$eirpr, lines(scaling[[20]]$aeir, scaling[[20]]$pr, col = clrs[20]))
```

### Drug taking 

```{r, eval=F}
sip = xds_setup_cohort(Xname = "SIP", F_season=Fsin)
sip$Xpar[[1]]$eta = 1/40
xde_scaling_eir(sip, 25) -> sip
```


```{r, eval=F}
sip1 = setup_exposure_nb(sip, 1/50)
xde_scaling_eir(sip1, 25) -> sip1
```

```{r, eval=F}
with(sis$outputs$eirpr, plot(aeir, pr, type = "l", log = "x", xaxt= "n", xlab = "aEIR", ylab = "PR"))
axis(1, 10^(-1:3), c(0.1, 1, 10, 100, 1000))
with(sip$outputs$eirpr, lines(aeir, pr, col = "darkorange"))
with(sip1$outputs$eirpr, lines(aeir, pr, col = "brown"))
``` 



### Travel

```{r, eval=F}
sis5 <- setup_static_travel(sis, 0.05)
sis5 <- setup_travel_eir(sis5,  travelEIR = 5/365)

xde_scaling_eir(sis5, 25) -> sis5
```


```{r, eval=F}
with(sis$outputs$eirpr, plot(aeir, pr, type = "l", log = "x", xaxt= "n", xlab = "aEIR", ylab = "PR"))
axis(1, 10^(-1:3), c(0.1, 1, 10, 100, 1000))
with(sis5$outputs$eir, lines(aeir, pr, col = "darkgreen")) 
```

