---
title: "Scaling Relationships"
subtitle: "Antimalarial Drugs"
editor:
  mode: source
bibliography: data/refs.bib
csl: data/plos.csl 
format: html
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
---

```{r}
library(ramp.xds)
library(ramp.library)
library(ramp.work)
```

```{r sis}
sis <- readRDS("./models/sis.rds")
```

```{r}
Xo = list(xi=2/365, rho=0.1)
```

```{r, eval=F}
sip <- xds_setup_eir(Xname = "SIP", Xopts=Xo)
```

```{r, eval=F}
sip <- xds_setup_eir(Xname = "SIP", Xopts=Xo)
xd_scaling(sip, 25) -> sip 
```

```{r sip scaling, echo=F}
if(file.exists("./models/sip.rds")){
  sip <- readRDS("./models/sip.rds")
} else {
  sip <- xds_setup_eir(Xname = "SIP")
  xds_scaling(sip, 25) -> sip 
  saveRDS(sip, file="./models/sip.rds")
}
```

```{r, eval=F}
sipd <- xds_setup_eir(Xname = "SIPd", Xopts=Xo)
xds_scaling(sipd, 25) -> sipd 
```

```{r sipd scaling, echo=F}
if(file.exists("./models/sipd.rds")){
  sipd <- readRDS("./models/sipd.rds")
} else {
  sipd <- xds_setup_eir(Xname = "SIPd")
  xds_scaling(sipd, 25) -> sipd 
  saveRDS(sipd, file="./models/sipd.rds")
}
```

```{r}
xds_plot_eirpr(sis, grey(.8))
lines_eirpr(sip, "darkviolet")
lines_eirpr(sipd, "darkblue")
```
